#
# Copyright (c) 2012-2014 Andr√© Bargull
# Alle Rechte vorbehalten / All Rights Reserved.  Use is subject to license terms.
#
# <https://github.com/anba/es6draft>
#

language: java

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - TEST262_PATH='~/test262'
  matrix:
    - PROFILE='skip-external'
    - PROFILE='test262'

before_install:
  - if [[ $TRAVIS_JDK_VERSION = 'oraclejdk8' ]]; then sudo apt-get update; sudo apt-get install oracle-java8-installer; else true; fi

install:
  - if [[ $PROFILE = 'test262' ]]; then git clone --depth 1 --branch master git://github.com/tc39/test262.git "${TEST262_PATH}"; else true; fi
  - mvn install --show-version --batch-mode --quiet --errors -DskipTests=true

# before_script: <cmd>

script: mvn verify --batch-mode --activate-profiles "${PROFILE}"

# after_script: <cmd>

# after_success: <cmd>

# after_failure: <cmd>

notifications:
  email:
    on_success: always
    on_failure: always
